name: Merge master on staging

on:
  push:
    branches:
      - master

jobs:
  merge-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: staging
          github_token: ${{ github.token }}
